# DESCRIPTION: GitLab CI/CD for libRetro (NOT FOR GitLab-proper)

##############################################################################
################################# BOILERPLATE ################################
##############################################################################

.core-defs:
  variables:
    GIT_SUBMODULE_STRATEGY: recursive
    CORENAME: nuance
    CORE_ARGS: -DBUILD_LIBRETRO=ON

include:
  - project: 'libretro-infrastructure/ci-templates'
    file: '/linux-cmake.yml'
  - project: 'libretro-infrastructure/ci-templates'
    file: '/windows-cmake-mingw.yml'

stages:
  - build-prepare
  - build-shared

##############################################################################
#################################### STAGES ##################################
##############################################################################

libretro-build-linux-x64:
  extends:
    - .libretro-linux-cmake-x86_64
    - .core-defs

libretro-build-windows-x64:
  extends:
    - .libretro-windows-cmake-x86_64
    - .core-defs
