#ifndef EXECUTE_MUL_H
#define EXECUTE_MUL_H

#include "mpe.h"

NuanceHandlerProto Execute_ADDM;
NuanceHandlerProto Execute_ADDMImmediate;
NuanceHandlerProto Execute_SUBM;
NuanceHandlerProto Execute_SUBMImmediateReverse;
NuanceHandlerProto Execute_MULScalarShiftAcshift;
NuanceHandlerProto Execute_MULScalarShiftRightImmediate;
NuanceHandlerProto Execute_MULScalarShiftLeftImmediate;
NuanceHandlerProto Execute_MULImmediateShiftAcshift;
NuanceHandlerProto Execute_MULScalarShiftScalar;
NuanceHandlerProto Execute_MULImmediateShiftScalar;
NuanceHandlerProto Execute_MULImmediateShiftRightImmediate;
NuanceHandlerProto Execute_MULImmediateShiftLeftImmediate;
NuanceHandlerProto Execute_MUL_SVImmediateShiftImmediate;
NuanceHandlerProto Execute_MUL_SVScalarShiftImmediate;
NuanceHandlerProto Execute_MUL_SVScalarShiftSvshift;
NuanceHandlerProto Execute_MUL_SVRuShiftImmediate;
NuanceHandlerProto Execute_MUL_SVRuShiftSvshift;
NuanceHandlerProto Execute_MUL_SVRvShiftImmediate;
NuanceHandlerProto Execute_MUL_SVRvShiftSvshift;
NuanceHandlerProto Execute_MUL_SVVectorShiftImmediate;
NuanceHandlerProto Execute_MUL_SVVectorShiftSvshift;
NuanceHandlerProto Execute_MUL_PImmediateShiftImmediate;
NuanceHandlerProto Execute_MUL_PScalarShiftImmediate;
NuanceHandlerProto Execute_MUL_PScalarShiftSvshift;
NuanceHandlerProto Execute_MUL_PRuShiftImmediate;
NuanceHandlerProto Execute_MUL_PRuShiftSvshift;
NuanceHandlerProto Execute_MUL_PRvShiftImmediate;
NuanceHandlerProto Execute_MUL_PRvShiftSvshift;
NuanceHandlerProto Execute_MUL_PVectorShiftImmediate;
NuanceHandlerProto Execute_MUL_PVectorShiftSvshift;
NuanceHandlerProto Execute_DOTPScalarShiftImmediate;
NuanceHandlerProto Execute_DOTPScalarShiftSvshift;
NuanceHandlerProto Execute_DOTPVectorShiftImmediate;
NuanceHandlerProto Execute_DOTPVectorShiftSvshift;

#endif