#ifndef PRINTMUL_H
#define PRINTMUL_H

#include "mpe.h"

NuancePrintHandlerProto Print_ADDM;
NuancePrintHandlerProto Print_ADDMImmediate;
NuancePrintHandlerProto Print_SUBM;
NuancePrintHandlerProto Print_SUBMImmediateReverse;
NuancePrintHandlerProto Print_MULScalarShiftAcshift;
NuancePrintHandlerProto Print_MULScalarShiftRightImmediate;
NuancePrintHandlerProto Print_MULScalarShiftLeftImmediate;
NuancePrintHandlerProto Print_MULImmediateShiftAcshift;
NuancePrintHandlerProto Print_MULScalarShiftScalar;
NuancePrintHandlerProto Print_MULImmediateShiftScalar;
NuancePrintHandlerProto Print_MULImmediateShiftRightImmediate;
NuancePrintHandlerProto Print_MULImmediateShiftLeftImmediate;
NuancePrintHandlerProto Print_MUL_SVImmediateShiftImmediate;
NuancePrintHandlerProto Print_MUL_SVScalarShiftImmediate;
NuancePrintHandlerProto Print_MUL_SVScalarShiftSvshift;
NuancePrintHandlerProto Print_MUL_SVRuShiftImmediate;
NuancePrintHandlerProto Print_MUL_SVRuShiftSvshift;
NuancePrintHandlerProto Print_MUL_SVRvShiftImmediate;
NuancePrintHandlerProto Print_MUL_SVRvShiftSvshift;
NuancePrintHandlerProto Print_MUL_SVVectorShiftImmediate;
NuancePrintHandlerProto Print_MUL_SVVectorShiftSvshift;
NuancePrintHandlerProto Print_MUL_PImmediateShiftImmediate;
NuancePrintHandlerProto Print_MUL_PScalarShiftImmediate;
NuancePrintHandlerProto Print_MUL_PScalarShiftSvshift;
NuancePrintHandlerProto Print_MUL_PRuShiftImmediate;
NuancePrintHandlerProto Print_MUL_PRuShiftSvshift;
NuancePrintHandlerProto Print_MUL_PRvShiftImmediate;
NuancePrintHandlerProto Print_MUL_PRvShiftSvshift;
NuancePrintHandlerProto Print_MUL_PVectorShiftImmediate;
NuancePrintHandlerProto Print_MUL_PVectorShiftSvshift;
NuancePrintHandlerProto Print_DOTPScalarShiftImmediate;
NuancePrintHandlerProto Print_DOTPScalarShiftSvshift;
NuancePrintHandlerProto Print_DOTPVectorShiftImmediate;
NuancePrintHandlerProto Print_DOTPVectorShiftSvshift;

#endif
