#ifndef PROPAGATE_CONSTANTS_ECU_H
#define PROPAGATE_CONSTANTS_ECU_H

#include "PropagateConstants.h"

PropagateConstantsHandlerProto PropagateConstants_ECU_NOP;
PropagateConstantsHandlerProto PropagateConstants_Halt;
PropagateConstantsHandlerProto PropagateConstants_BRAAlways;
PropagateConstantsHandlerProto PropagateConstants_BRAAlways_NOP;
PropagateConstantsHandlerProto PropagateConstants_BRAConditional;
PropagateConstantsHandlerProto PropagateConstants_BRAConditional_NOP;
PropagateConstantsHandlerProto PropagateConstants_JMPAlwaysIndirect;
PropagateConstantsHandlerProto PropagateConstants_JMPAlwaysIndirect_NOP;
PropagateConstantsHandlerProto PropagateConstants_JMPConditionalIndirect;
PropagateConstantsHandlerProto PropagateConstants_JMPConditionalIndirect_NOP;
PropagateConstantsHandlerProto PropagateConstants_JSRAlways;
PropagateConstantsHandlerProto PropagateConstants_JSRAlways_NOP;
PropagateConstantsHandlerProto PropagateConstants_JSRConditional;
PropagateConstantsHandlerProto PropagateConstants_JSRConditional_NOP;
PropagateConstantsHandlerProto PropagateConstants_JSRAlwaysIndirect;
PropagateConstantsHandlerProto PropagateConstants_JSRAlwaysIndirect_NOP;
PropagateConstantsHandlerProto PropagateConstants_JSRConditionalIndirect;
PropagateConstantsHandlerProto PropagateConstants_JSRConditionalIndirect_NOP;
PropagateConstantsHandlerProto PropagateConstants_RTSAlways;
PropagateConstantsHandlerProto PropagateConstants_RTSAlways_NOP;
PropagateConstantsHandlerProto PropagateConstants_RTSConditional;
PropagateConstantsHandlerProto PropagateConstants_RTSConditional_NOP;
PropagateConstantsHandlerProto PropagateConstants_RTI1Conditional;
PropagateConstantsHandlerProto PropagateConstants_RTI1Conditional_NOP;
PropagateConstantsHandlerProto PropagateConstants_RTI2Conditional;
PropagateConstantsHandlerProto PropagateConstants_RTI2Conditional_NOP;

#endif
