#ifndef PROPAGATE_CONSTANTS_MUL_H
#define PROPAGATE_CONSTANTS_MUL_H

#include "PropagateConstants.h"

PropagateConstantsHandlerProto PropagateConstants_ADDM;
PropagateConstantsHandlerProto PropagateConstants_ADDMImmediate;
PropagateConstantsHandlerProto PropagateConstants_SUBM;
PropagateConstantsHandlerProto PropagateConstants_SUBMImmediateReverse;
PropagateConstantsHandlerProto PropagateConstants_MULScalarShiftAcshift;
PropagateConstantsHandlerProto PropagateConstants_MULScalarShiftRightImmediate;
PropagateConstantsHandlerProto PropagateConstants_MULScalarShiftLeftImmediate;
PropagateConstantsHandlerProto PropagateConstants_MULImmediateShiftAcshift;
PropagateConstantsHandlerProto PropagateConstants_MULScalarShiftScalar;
PropagateConstantsHandlerProto PropagateConstants_MULImmediateShiftScalar;
PropagateConstantsHandlerProto PropagateConstants_MULImmediateShiftRightImmediate;
PropagateConstantsHandlerProto PropagateConstants_MULImmediateShiftLeftImmediate;
PropagateConstantsHandlerProto PropagateConstants_MUL_SVImmediateShiftImmediate;
PropagateConstantsHandlerProto PropagateConstants_MUL_SVScalarShiftImmediate;
PropagateConstantsHandlerProto PropagateConstants_MUL_SVScalarShiftSvshift;
PropagateConstantsHandlerProto PropagateConstants_MUL_SVRuShiftImmediate;
PropagateConstantsHandlerProto PropagateConstants_MUL_SVRuShiftSvshift;
PropagateConstantsHandlerProto PropagateConstants_MUL_SVRvShiftImmediate;
PropagateConstantsHandlerProto PropagateConstants_MUL_SVRvShiftSvshift;
PropagateConstantsHandlerProto PropagateConstants_MUL_SVVectorShiftImmediate;
PropagateConstantsHandlerProto PropagateConstants_MUL_SVVectorShiftSvshift;
PropagateConstantsHandlerProto PropagateConstants_MUL_PImmediateShiftImmediate;
PropagateConstantsHandlerProto PropagateConstants_MUL_PScalarShiftImmediate;
PropagateConstantsHandlerProto PropagateConstants_MUL_PScalarShiftSvshift;
PropagateConstantsHandlerProto PropagateConstants_MUL_PRuShiftImmediate;
PropagateConstantsHandlerProto PropagateConstants_MUL_PRuShiftSvshift;
PropagateConstantsHandlerProto PropagateConstants_MUL_PRvShiftImmediate;
PropagateConstantsHandlerProto PropagateConstants_MUL_PRvShiftSvshift;
PropagateConstantsHandlerProto PropagateConstants_MUL_PVectorShiftImmediate;
PropagateConstantsHandlerProto PropagateConstants_MUL_PVectorShiftSvshift;
PropagateConstantsHandlerProto PropagateConstants_DOTPScalarShiftImmediate;
PropagateConstantsHandlerProto PropagateConstants_DOTPScalarShiftSvshift;
PropagateConstantsHandlerProto PropagateConstants_DOTPVectorShiftImmediate;
PropagateConstantsHandlerProto PropagateConstants_DOTPVectorShiftSvshift;

#endif
