#ifndef PROPAGATE_CONSTANTS_RCU_H
#define PROPAGATE_CONSTANTS_RCU_H

#include "PropagateConstants.h"

PropagateConstantsHandlerProto PropagateConstants_DECRc0;
PropagateConstantsHandlerProto PropagateConstants_DECRc1;
PropagateConstantsHandlerProto PropagateConstants_DECBoth;
PropagateConstantsHandlerProto PropagateConstants_ADDRImmediate;
PropagateConstantsHandlerProto PropagateConstants_ADDRImmediateOnly;
PropagateConstantsHandlerProto PropagateConstants_ADDRScalar;
PropagateConstantsHandlerProto PropagateConstants_ADDRScalarOnly;
PropagateConstantsHandlerProto PropagateConstants_MVRImmediate;
PropagateConstantsHandlerProto PropagateConstants_MVRImmediateOnly;
PropagateConstantsHandlerProto PropagateConstants_MVRScalar;
PropagateConstantsHandlerProto PropagateConstants_MVRScalarOnly;
PropagateConstantsHandlerProto PropagateConstants_Range;
PropagateConstantsHandlerProto PropagateConstants_RangeOnly;
PropagateConstantsHandlerProto PropagateConstants_Modulo;
PropagateConstantsHandlerProto PropagateConstants_ModuloOnly;

#endif
